### ISSUE TITLE
Errors verbose and leak implementation details

### ISSUE THREAD

**Issue by RhysU** [Russell91/pythonpy#54]
Observe lots of unhelpful details on a usage error...

    $ py '[range(3)' 2>/dev/null
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/pythonpy/__main__.py", line 154, in <module>
        result = eval(args.expression)
      File "<string>", line 1
        [range(3)
                ^
    SyntaxError: unexpected EOF while parsing

...where only the last three lines are useful.

**Comment by Russell91** [comment]
I made some changes to reduce the verbose exceptions problem. Currently, I'm using traceback.format_exc() to write errors, which was better than python's naive response. There is room for improvement though. If anyone has a better way I'd be very open to accepting a pull request. I think this is low hanging fruit.

**Comment by abarnert** [comment]
This isn't as easy as it sounds. Although `format_exc` and friends take a `limit`, it's a static value, and it limits from the wrong direction. So you have to extract the traceback, filter it, and format it manually.

The problem is that 2.x doesn't have enough functionality in `traceback` to do that—and, while 3.x does, it's a huge pain to handle chained exceptions manually, and many exceptions worth printing are going to be chained.

One hacky solution is to just use `format_exception`, then filter the result:

    except Exception as e:
        header = 'File "{}"'.format(__file__)
        lines = traceback.format_exception(type(e), e, e.__traceback__)
        lines = (line for line in lines if not line.lstrip().startswith(header))
        return ''.join(lines)

For 2.x, I don't think `Exception.__traceback__` exists (or maybe it does in 2.7, but not 2.6), but since you're doing this inside the `except` block anyway, `sys.last_traceback` will have it, or just do:

    except Exception:
        header = 'File "{}"'.format(__file__)
        lines = traceback.format_exception(*sys.exc_info())
        lines = (line for line in lines if not line.lstrip().startswith(header))
        return ''.join(lines)

And that ought to work with everything from 2.4+, including 3.x (although I haven't tested that).

You might also want to filter out lines starting with  `File "<string>"` (the user's actual expression, and any lambdas he defined and called in that expression) because they'll have no text to print. But on the other hand, if the user's expression calls something that itself evaluates a string, you probably want to distinguish that from you evaluating the user's expression. So I left it in.

(Note that in the case of a `SyntaxError`, the part that shows the user's text is actually part of the exception, even though it _looks_ like part of the traceback.)

Anyway, here's what you get in 3.x (using `requests`, because it's pretty conscientious about chaining together everything you could possibly want):

    $ py '2+"a"'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    TypeError: unsupported operand type(s) for +: 'int' and 'str'

    $ py3 '2+"a"'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    TypeError: unsupported operand type(s) for +: 'int' and 'str'

    $ py '[range(3)'
    Traceback (most recent call last):
      File "<string>", line 1
        [range(3)
                ^
    SyntaxError: unexpected EOF while parsing

    $ py3 '[range(3)'
    Traceback (most recent call last):
      File "<string>", line 1
        [range(3)
                ^
    SyntaxError: unexpected EOF while parsing

    $ py 'requests.get("http://1.2.3.4.5")'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Library/Python/2.7/site-packages/requests/api.py", line 65, in get
        return request('get', url, **kwargs)
      File "/Library/Python/2.7/site-packages/requests/api.py", line 49, in request
        response = session.request(method=method, url=url, **kwargs)
      File "/Library/Python/2.7/site-packages/requests/sessions.py", line 461, in request
        resp = self.send(prep, **send_kwargs)
      File "/Library/Python/2.7/site-packages/requests/sessions.py", line 573, in send
        r = adapter.send(request, **kwargs)
      File "/Library/Python/2.7/site-packages/requests/adapters.py", line 415, in send
        raise ConnectionError(err, request=request)
    ConnectionError: ('Connection aborted.', gaierror(8, 'nodename nor servname provided, or not known'))


    $ py3 'requests.get("http://1.2.3.4.5")'
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 478, in urlopen
        body=body, headers=headers)
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 285, in _make_request
        conn.request(method, url, **httplib_request_kw)
    [snip]
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/socket.py", line 530, in getaddrinfo
        for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    socket.gaierror: [Errno 8] nodename nor servname provided, or not known
    
    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/adapters.py", line 324, in send
        timeout=timeout
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 528, in urlopen
        raise MaxRetryError(self, url, e)
    requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='1.2.3.4.5', port=80): Max retries exceeded with url: / (Caused by <class 'socket.gaierror'>: [Errno 8] nodename nor servname provided, or not known)
    
    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/api.py", line 55, in get
        return request('get', url, **kwargs)
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/api.py", line 44, in request
        return session.request(method=method, url=url, **kwargs)
    [snip]
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/adapters.py", line 372, in send
        raise ConnectionError(e)
    requests.exceptions.ConnectionError: HTTPConnectionPool(host='1.2.3.4.5', port=80): Max retries exceeded with url: / (Caused by <class 'socket.gaierror'>: [Errno 8] nodename nor servname provided, or not known)

(The `[snip]` parts are me manually snipping the output, because it's _huge_. But anyway, as you can see, you get exactly the same traceback you'd get from `requests`, with `safe_eval` and everything above it not visible.)

Anyway, if this is what you want, I can create a pull request.

**Comment by Russell91** [comment]
Okay, this seems like an improvement. This guy (https://github.com/edk0/spy) claims he has better error handling than pythonpy. Maybe you can check out his tool as well and make sure that pythonpy will be at least as good as what he has after your pull request?

**Comment by abarnert** [comment]
I've had some problems installing `spy` on my main system because it has the same name as https://pypi.python.org/pypi/spy/ (which I'm not using, but it's somehow getting in the way anyway), but I'll get it working and look at it.

Meanwhile, the biggest problem with my change is that when you're trying to debug `pythonpy` itself, you're missing the relevant part of the traceback. But hopefully your users won't have that problem unless they're doing ugly things to hack up your code (as I have been…).

By the way, the second pull request should be the same as the first, but with the git tangle untangled, but you might want to check it.

**Comment by abarnert** [comment]
OK, got it.

`spy` strips out the `spy` machinery using a similar hack, but it then adds another (pretty cool) hack to add the "fragment" (expression) into the output in the appropriate place. So, instead of this:

    $ py3 'None+2'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

You get this:

    $ spy 'None+2'
    Traceback (most recent call last):
      Fragment 1
        None+2
        input to fragment was <SpyFile stream='<stdin>'>
    TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

The hack is pretty simple. For example, if you define and call a lambda in your fragment, that still shows up as empty code:

    $ spy '(lambda: None+2)()'
    Traceback (most recent call last):
      Fragment 1
        (lambda: None+2)()
        input to fragment was <SpyFile stream='<stdin>'>
      File "Fragment 1", line 1, in <lambda>
    TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

I think the `Fragment 1` is a bit confusing (especially since it shows up as `File "Fragment 1"` in things like the `<lambda>`). And of course `py` only has one expression, and only one input, so the extra information doesn't tell you anything. So it might be better to keep it consistent with standard Python tracebacks, like this:

    $ py3 'None+2'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
        (lambda: None+2)()
    TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
      File "<string>", line 1, in <lambda>
    TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

I think I can hack that up pretty quickly; let me try.

**Comment by abarnert** [comment]
OK, pull request #59 should now have this fix as well:

    $ py3 '(lambda: None+2)()'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
        (lambda: None+2)()
      File "<string>", line 1, in <lambda>
    TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
