### ISSUE TITLE
cannot import name SIGPIPE

### ISSUE THREAD

**Issue by hanxiaomax** [Russell91/pythonpy#70]
```
$ py '3*1.5'
Traceback (most recent call last):
  File "c:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\Python27\Scripts\py.exe\__main__.py", line 5, in <module>
  File "c:\Python27\lib\site-packages\pythonpy\__main__.py", line 10, in <module
>
    from signal import signal, SIGPIPE, SIG_DFL
ImportError: cannot import name SIGPIPE
```

I installed pythonpy through pip ,however, I got this  trouble when I run it .Any tips about that?

**Comment by Russell91** [comment]
Ah, this really confused me until I realized that you are running windows. You should check out http://github.com/Russell91/pythonwpy. Not very popular, but fully functional.
